name: aumiau_app
description: Um app de agendamento pet usando Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  #sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  provider: ^6.1.3
  cupertino_icons: ^1.0.8
  cloud_firestore_web: ^4.4.7
  oktoast: ^3.4.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
